baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "projects"
    url = "/projects/"
    weight = -100

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "blog section"
    url = "/blog/"
    weight = -90
