baseURL = "http://example.org/"
languageCode = "en-GB"
title = "Moppler"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "projects"
    url = "/projects/"
    weight = -100

